
name: Update Azure Function App Settings

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  update-app-settings:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to Azure using Service Principal JSON
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Apply only the provided JSON content
      - name: Set Azure Function App Settings from JSON
        run: |
          # Save the JSON secret to config.json
          echo '${{ secrets.APP_CONFIG_JSON }}' > config.json
          
          # Extract key-value pairs, remove "Values." prefix, and apply them to Azure
          jq -r 'paths(scalars) as $p | "\($p | join("."))=\(getpath($p))"' config.json | while IFS= read -r line; do
            key=$(echo $line | cut -d= -f1)
            value=$(echo $line | cut -d= -f2-)

            # Remove 'Values.' prefix if present
            if [[ $key == Values.* ]]; then
              key=$(echo $key | sed 's/^Values\.//')
            fi

            # Apply each key-value pair to Azure Function
            az functionapp config appsettings set \
              --name testinadl \  # <-- Replace with your Function App name
              --resource-group acdl-0-poc-rg \  # <-- Replace with your Resource Group
              --settings "$key=$value"
          done

      # Step 4: Logout from Azure after completion
      - name: Logout from Azure
        run: |
          az logout
