
name: Update Azure Function App Settings

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  update-app-settings:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to Azure using Service Principal JSON
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Extract and flatten JSON as environment variables
      - name: Flatten and set JSON environment variables
        run: |
          # Save JSON secret to config.json
          echo '${{ secrets.APP_CONFIG_JSON }}' > config.json
          
          # Flatten the JSON and create environment variables
          jq -r 'paths(scalars) as $p | "\($p | join("__"))=\(getpath($p))"' config.json | while IFS= read -r line; do
            # Replace spaces and special chars for Azure compatibility
            key=$(echo $line | cut -d= -f1 | sed 's/\[//g; s/\]//g; s/ //g')
            value=$(echo $line | cut -d= -f2-)

            # Print for debugging
            echo "Setting: $key=$value"

            # Set environment variable for GitHub
            echo "$key=$value" >> $GITHUB_ENV
          done

      # Step 4: Apply all environment variables as Azure Function App settings
      - name: Apply environment variables to Azure Function
        run: |
          # Loop through all flattened variables and apply them to Azure
          while IFS= read -r line; do
            key=$(echo "$line" | cut -d= -f1)
            value=$(echo "$line" | cut -d= -f2-)

            # Set key-value pairs in Azure Function App Settings
            az functionapp config appsettings set \
              --name testinadl \
              --resource-group acdl-0-poc-rg \
              --settings "$key=$value"
          done < <(jq -r 'paths(scalars) as $p | "\($p | join("__"))=\(getpath($p))"' config.json)

      # Step 5: Logout from Azure after completion
      - name: Logout from Azure
        run: |
          az logout
