name: Update Azure Function App Settings

on:
  workflow_dispatch:

jobs:
  update-app-settings:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to Azure using Service Principal JSON
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Extract JSON secret and create environment variables
      - name: Extract JSON and create environment variables
        run: |
          # Save JSON secret to a config.json file
          echo '${{ secrets.APP_CONFIG_JSON }}' > config.json
          
          # Read the JSON file and export as environment variables
          for key in $(jq -r 'keys[]' config.json); do
            value=$(jq -r --arg key "$key" '.[$key]' config.json)
            echo "$key=$value" >> $GITHUB_ENV
          done

      # Step 4: Update Azure Function App settings with environment variables
      - name: Apply environment variables to Azure Function
        run: |
          # Loop through each key-value pair and set them in Azure Function
          for key in $(jq -r 'keys[]' config.json); do
            value=$(jq -r --arg key "$key" '.[$key]' config.json)
            az functionapp config appsettings set \
              --name testinadl \
              --resource-group acdl-0-poc-rg \
              --settings "$key=$value"
          done

      # Step 5: Logout from Azure after completion (optional cleanup)
      - name: Logout from Azure
        run: |
          az logout
