name: Update Azure Function App Settings

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  update-app-settings:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to Azure using Service Principal JSON
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Set the entire JSON as a single environment variable
      - name: Set entire JSON as APP_CONFIG_JSON
        run: |
          # Store JSON from secret into config.json
          echo '${{ secrets.APP_CONFIG_JSON }}' > config.json
          
          # Escape and compress JSON for Azure App Settings (removes newlines and spaces)
          JSON_STRING=$(jq -c . config.json)

          # Save JSON to GITHUB_ENV to pass to next step
          echo "APP_CONFIG_JSON=$JSON_STRING" >> $GITHUB_ENV

      # Step 4: Apply JSON as a single application setting
      - name: Update Azure Function App Settings with nested JSON
        run: |
          # Set the entire JSON in Azure Function App Settings
          az functionapp config appsettings set \
            --name testinadl \
            --resource-group acdl-0-poc-rg \
            --settings "APP_CONFIG_JSON=$APP_CONFIG_JSON"

      # Step 5: Logout from Azure after completion (optional cleanup)
      - name: Logout from Azure
        run: |
          az logout
